name: Image Scraper

on:
  schedule:
    - cron: "0 * * * *"  # run every hour
  workflow_dispatch:

permissions:
  contents: write  # 👈 allow pushing commits

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests openpyxl pillow

      - name: Run scraper
        run: python imagescrape.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add thumbnails/*.png || true
          git commit -m "Update thumbnails [skip ci]" || echo "No changes to commit"
          git push
